version: "3.9"

services:
  sitl:
    image: radarku/sitl-swarm
    ports:
      - 5770:5770
      - 5780:5780
      - 5790:5790
      - 5800:5800
      # - 5810:5810
      # - 5820:5820
      # - 5830:5830
      # - 5840:5840
      # - 5850:5850
    environment:
      - INSTANCE=1
      # - NUMCOPTERS=10
      - NUMCOPTERS=5
      - LAT=35.729498
      - INCREMENTSTEPLAT=0.0000
      - LON=-78.696408
      - INCREMENTSTEPLON=-0.0003
      - ALT=0

  ground-service:
    build: ./ground
    ports:
      - 8080:8080

  drone-1:
    build: ./drone
    ports:
      - 14551:5762
    environment:
      - PORT=5770
      - GROUNDPORT=5761
      - MAVHOST=:5761
      - DRONEID=drone1
      - SYSID=241
      - TARGETCOORD=35.7262,-78.6948
    depends_on:
      - sitl
    command: ["./wait-for-it.sh", "--timeout=0", "sitl:5770", "--", "./start.sh"]

  drone-2:
    build: ./drone
    ports:
      - 14552:5762
    environment:
      - PORT=5780
      - GROUNDPORT=5762
      - MAVHOST=:5762
      - DRONEID=drone2
      - SYSID=242
      - TARGETCOORD=35.7262,-78.6951
    depends_on:
      - sitl
    command: ["./wait-for-it.sh", "--timeout=0", "sitl:5780", "--", "./start.sh"]
  
  drone-3:
    build: ./drone
    ports:
      - 14553:5762
    environment:
      - PORT=5790
      - GROUNDPORT=5763
      - MAVHOST=:5763
      - DRONEID=drone3
      - SYSID=243
      - TARGETCOORD=35.7262,-78.6954
    depends_on:
      - sitl
    command: ["./wait-for-it.sh", "--timeout=0", "sitl:5790", "--", "./start.sh"]
  
  drone-4:
    build: ./drone
    ports:
      - 14554:5762
    environment:
      - PORT=5800
      - GROUNDPORT=5764
      - MAVHOST=:5764
      - DRONEID=drone4
      - SYSID=244
      - TARGETCOORD=35.7262,-78.6957
    depends_on:
      - sitl
    command: ["./wait-for-it.sh", "--timeout=0", "sitl:5800", "--", "./start.sh"]
  
  # drone-5:
  #   build: ./drone
  #   ports:
  #     - 14555:5762
  #   environment:
  #     - PORT=5810
  #     - GROUNDPORT=5765
  #     - MAVHOST=:5765
  #     - DRONEID=drone5
  #     - SYSID=245
  #     - TARGETCOORD=35.7262,-78.6960
  #   depends_on:
  #     - sitl
  #   command: ["./wait-for-it.sh", "--timeout=0", "sitl:5810", "--", "./start.sh"]
  
  # drone-6:
  #   build: ./drone
  #   ports:
  #     - 14556:5762
  #   environment:
  #     - PORT=5820
  #     - GROUNDPORT=5766
  #     - MAVHOST=:5766
  #     - DRONEID=drone6
  #     - SYSID=246
  #     - TARGETCOORD=35.7262,-78.6963
  #   depends_on:
  #     - sitl
  #   command: ["./wait-for-it.sh", "--timeout=0", "sitl:5820", "--", "./start.sh"]

  # drone-7:
  #   build: ./drone
  #   ports:
  #     - 14557:5762
  #   environment:
  #     - PORT=5830
  #     - GROUNDPORT=5767
  #     - MAVHOST=:5767
  #     - DRONEID=drone7
  #     - SYSID=247
  #     - TARGETCOORD=35.7262,-78.6966
  #   depends_on:
  #     - sitl
  #   command: ["./wait-for-it.sh", "--timeout=0", "sitl:5830", "--", "./start.sh"]
  
  # drone-8:
  #   build: ./drone
  #   ports:
  #     - 14558:5762
  #   environment:
  #     - PORT=5840
  #     - GROUNDPORT=5768
  #     - MAVHOST=:5768
  #     - DRONEID=drone8
  #     - SYSID=248
  #     - TARGETCOORD=35.7262,-78.6969
  #   depends_on:
  #     - sitl
  #   command: ["./wait-for-it.sh", "--timeout=0", "sitl:5840", "--", "./start.sh"]
  
  # drone-9:
  #   build: ./drone
  #   ports:
  #     - 14559:5762
  #   environment:
  #     - PORT=5850
  #     - GROUNDPORT=5769
  #     - MAVHOST=:5769
  #     - DRONEID=drone9
  #     - SYSID=249
  #     - TARGETCOORD=35.7262,-78.6972
  #   depends_on:
  #     - sitl
  #   command: ["./wait-for-it.sh", "--timeout=0", "sitl:5850", "--", "./start.sh"]
